export const ACCESS_TOKEN_KEY = "LOCAL_TOKEN";

export const ACCESS_TOKEN_FAILED = "ACCESS_TOKEN_FAILED";

export const COLUMN_OPTIONS = "COLUMN_OPTIONS";

export const STORAGE_COMPANY_ID = "companyId"