query user_getCurrentComplexManager {
    user_getCurrentComplexManager {
        result {
            complexManagerComplexes {
                complexId
                complex {
                    name
                    id
                }
            }
            userType
            firstName
            middleName
            lastName
            fullName
            photoUrl
            gender
            dateOfBirth
            phoneNumber
            activeStatus
            isActive
            isInactive
            approvalStatus
            accountDeleted
            externalId
            email
            id
            isDeleted
            createdDate
            lastModifiedDate
        }
        status
    }
}
